service: lambda-invoke

plugins:
  - serverless-offline

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: "*"
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  environment:
    # Sets the log level
    LOG_LEVEL: info

functions:
  example-one:
    name: example-one-${self:provider.stage}
    events:
      - http:
          method: get
          path: test-handler
    handler: dist/handler.exampleOne

  example-two:
    name: example-two-${self:provider.stage}
    events:
      - http:
          method: get
          path: test-handler-two
    handler: dist/handler.exampleTwo

  example-three:
    name: example-three-${self:provider.stage}
    events:
      - http:
          method: get
          path: test-handler-three
    handler: dist/handler.exampleThree